header:
  license:
    content: |
      SPDX-License-Identifier: LGPL-2.1-or-later
  paths-ignore:
    - 'target'
    - '**/*.toml'
    - '**/*.lock'
    - '**/*.yml'
    - '**/*.md'
    - 'CHANGELOG'
    - 'LICENSE-MIT'
    - '.gitignore'

  comment: on-failure