name: license

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - base
  workflow_dispatch:

jobs:
  check-license:
    name: Check License
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - uses: actions/checkout@v3
      - name: Check License Header - Rust
        uses: apache/skywalking-eyes@v0.3.0
        with:
          config: .licenserc.rust.yaml

      - name: Check License Header - Python
        uses: apache/skywalking-eyes@v0.3.0
        with:
          config: .licenserc.python.yaml
