name: license

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - update/license_header_chech

jobs:
  check-license:
    name: Check License
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - uses: apache/skywalking-eyes/header@main
      - name: Check License Header
